// Code generated by metricsgen. DO NOT EDIT.

package txindex

import (
	"github.com/go-kit/kit/metrics/discard"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	stdprometheus "github.com/prometheus/client_golang/prometheus"
)

func PrometheusMetrics(namespace string, labelsAndValues ...string) *Metrics {
	labels := []string{}
	for i := 0; i < len(labelsAndValues); i += 2 {
		labels = append(labels, labelsAndValues[i])
	}
	return &Metrics{
		GatherEventsSeconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "gather_events_seconds",
			Help:      "Time spent receiving all transaction events for one block.",

			Buckets: stdprometheus.ExponentialBucketsRange(0.0001, 10, 16),
		}, labels).With(labelsAndValues...),
		BlockIndexSeconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "block_index_seconds",
			Help:      "Time spent writing one block to the block index.",

			Buckets: stdprometheus.ExponentialBucketsRange(0.0001, 10, 16),
		}, labels).With(labelsAndValues...),
		TxIndexSeconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "tx_index_seconds",
			Help:      "Time spent writing one transaction batch to the transaction index.",

			Buckets: stdprometheus.ExponentialBucketsRange(0.0001, 10, 16),
		}, labels).With(labelsAndValues...),
		BlockTotalSeconds: prometheus.NewHistogramFrom(stdprometheus.HistogramOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "block_total_seconds",
			Help:      "End-to-end time spent processing one indexed block.",

			Buckets: stdprometheus.ExponentialBucketsRange(0.0001, 10, 16),
		}, labels).With(labelsAndValues...),
		IndexedTxsTotal: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "indexed_txs_total",
			Help:      "Number of transactions handed to the transaction index.",
		}, labels).With(labelsAndValues...),
	}
}

func NopMetrics() *Metrics {
	return &Metrics{
		GatherEventsSeconds: discard.NewHistogram(),
		BlockIndexSeconds:   discard.NewHistogram(),
		TxIndexSeconds:      discard.NewHistogram(),
		BlockTotalSeconds:   discard.NewHistogram(),
		IndexedTxsTotal:     discard.NewCounter(),
	}
}
